### ISSUE TITLE
最近去哪儿好像封闭了这个端口……

### ISSUE THREAD

**Issue by yujiye** [NGUWQ/Python3Spider#1]
G:\spider\Python3Spider\dataanalysis>python qunarhotel.py

DevTools listening on ws://127.0.0.1:5250/devtools/browser/c706af31-aa3c-4276-8997-c49766b58f20
--------Waiting for TOCITY focus>>>>>>>>>
--------Get 得到城市输入框，准备清除>>>>>>>
--------清除结束，输入目标城市>>>>>>>
[7472:8948:0104/213858.047:ERROR:platform_sensor_reader_win.cc(242)] NOT IMPLEMENTED
这个城市共有-【%d】-页 382
目前第-【%d】-页 1
qunarhotel.py:127: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  db[collection].insert(hotel)
Traceback (most recent call last):
  File "qunarhotel.py", line 149, in <module>
    selecthotel()
  File "qunarhotel.py", line 86, in selecthotel
    parse(response)
  File "qunarhotel.py", line 115, in parse
    savetomongodb(hotel)
  File "qunarhotel.py", line 127, in savetomongodb
    db[collection].insert(hotel)
  File "C:\Users\Alex\python\lib\site-packages\pymongo\collection.py", line 3161, in insert
    check_keys, manipulate, write_concern)
  File "C:\Users\Alex\python\lib\site-packages\pymongo\collection.py", line 607, in _insert
    bypass_doc_val, session)
  File "C:\Users\Alex\python\lib\site-packages\pymongo\collection.py", line 595, in _insert_one
    acknowledged, _insert_command, session)
  File "C:\Users\Alex\python\lib\site-packages\pymongo\mongo_client.py", line 1247, in _retryable_write
    with self._tmp_session(session) as s:
  File "C:\Users\Alex\python\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Alex\python\lib\site-packages\pymongo\mongo_client.py", line 1576, in _tmp_session
    s = self._ensure_session(session)
  File "C:\Users\Alex\python\lib\site-packages\pymongo\mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Alex\python\lib\site-packages\pymongo\mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Alex\python\lib\site-packages\pymongo\mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Alex\python\lib\site-packages\pymongo\topology.py", line 427, in get_server_session
    None)
  File "C:\Users\Alex\python\lib\site-packages\pymongo\topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

G:\spider\Python3Spider\dataanalysis>[7472:7912:0104/214025.275:ERROR:platform_sensor_reader_win.cc(242)] NOT IMPLEMENTED

G:\spider\Python3Spider\dataanalysis>

**Comment by yujiye** [comment]
不知道怎么处理？
